version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test
